### ISSUE TITLE
No python3 mode in CodeMirror

### ISSUE THREAD

**Issue by sergeyepimakhov** [minrk/thebelab#169] opened 2019-10-25 21:00 UTC
https://github.com/minrk/thebelab/blob/c58c2ee3ebe603c9a8413f815dcab06a657ef3e6/src/thebelab.js#L249

I guess there is no 'python3' mode in CodeMirror. Only the 'python' mode (default version is 3).

https://github.com/codemirror/CodeMirror/tree/master/mode/python/python.js

**Comment by choldgraf** [comment] 2019-10-27 00:31
yep - I believe this one is a dupe of https://github.com/minrk/thebelab/issues/96

**Closed** 2019-10-29 17:54 UTC
